name: Update Starred Repositories and Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  schedule:
    - cron: '5 4 * * *'   # Run daily at 4:05 AM
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-stars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Update README and Build Web
        uses: mxvsh/starkit@v2.4.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-username: ${{ github.actor }}
          build-web: true
