name: Update Starred Repositories

on:
  schedule:
    - cron: '5 4 * * *'   # Run daily at 4:05 AM
  workflow_dispatch:      # Allow manual trigger

permissions: write-all

jobs:
  update-stars:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Update README with Starred Repositories
        uses: mxvsh/starkit@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-username: ${{ github.actor }}
          build-web: true
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
